# Generated by Django 5.1.3 on 2024-11-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('empID', models.IntegerField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=255)),
                ('empDesignation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectID', models.IntegerField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=255)),
                ('projectProgress', models.IntegerField()),
                ('projectDomain', models.CharField(max_length=255)),
                ('projectLead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butler.employee')),
            ],
        ),
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('aID', models.IntegerField(primary_key=True, serialize=False)),
                ('eID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butler.employee')),
                ('projID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butler.project')),
            ],
        ),
    ]
