# Generated by Django 5.1.3 on 2024-11-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butler', '0003_alter_task_project_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
