# Generated by Django 5.1.3 on 2024-11-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butler', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedEmployee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='butler.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butler.project'),
        ),
    ]
