# Generated by Django 5.1.3 on 2024-11-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butler', '0006_alter_task_assignedemployee_id_alter_task_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignedEmployee_id',
            new_name='assignedEmployee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
