# Generated by Django 5.1.3 on 2024-11-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butler', '0008_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
